export const PostsData=[
    {
        id:1,
        name:"faokfoa",
        content:"fkakfakf",
    },
    {
        id:2,
        name:"ieinvk",
        content:"lfpsoo",
    },
    {
        id:3,
        name:"fpspke",
        content:"qfdjo",
    },
    {
        id:4,
        name:"moehap",
        content:"kodfojhhe",
    },
]